### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by suecom** [sharetribe/flex-template-web#1040]
You need to include 'inquirer' for config to run (package.json) - it's not being installed from the current master

**Comment by suecom** [comment]
I see inquirer is in the devDependancies (package.json), but these are not being used (installed) with 'yarn install' on a fresh build?

**Comment by Gnito** [comment]
@suecom, they should be installed on local environment. 

Are you sure that your `NODE_ENV` is not set to _production_? Yarn won’t install devDependencies by default, if that environment variable is set to ”production”.

**Comment by suecom** [comment]
NODE_ENV wasn't set? I'd drop this.
