### ISSUE TITLE
[feature] Add possibility to use external libraries

### ISSUE THREAD

**Issue by EugeneSnihovsky** [sharetribe/flex-template-web#1205]
For now I can't find any solution to import
- bootstrap css (in src/index.js `import '../node_modules/bootstrap/dist/css/bootstrap.css';` or `import 'bootstrap/dist/css/bootstrap.css';`)
- flexboxgrid css or https://www.npmjs.com/package/react-flexbox-grid

Probably build scripts should be modified for this

**Comment by Gnito** [comment]
Hi @EugeneSnihovsky,

Good suggestion, we should research for better ways to import global CSS libs that are not using [CSS Modules](https://github.com/css-modules/css-modules). So, [FTW is relying on CSS Modules](https://www.sharetribe.com/docs/guides/how-to-customize-ftw-styles/#styling-components) to get rid off CSS specificity hell, which easily becomes a problem on projects this size - especially when new customizers (who, by definition, are not familiar with the complete app setup) starts to create their own styles. 

Furthermore, we started to use CSS Modules before Create React App (CRA) took it to its own tech stack. (`sharetribe-scripts` dependency is a fork of CRA) So, FTW's Webpack build script is not behaving the same way as in default CRA implementation - i.e. all the CSS files are expected to use CSS Modules. 

Anyway, back to your problem: 
it is possible to use plain CSS files. You could follow the setup we have for React Dates:

1. Add the CSS file into [`public/static` directory](https://github.com/sharetribe/flex-template-web/tree/master/public/static).
2. Link the CSS file in the [index.html](https://github.com/sharetribe/flex-template-web/blob/master/public/index.html#L87)
3. There are two ways to use global classes:
  a. Use them directly `<span class="importedGlobalClass">` 
      (Personally, I don't recommend this.)
  b. [Use those global classes from inside classes using CSS Modules](https://github.com/sharetribe/flex-template-web/blob/master/src/components/FieldDateInput/DateInput.css#L26) to avoid class name collisions between components.

I close this issue for now, but I'll record this as a feature request: _make global CSS files easier to import_.

**Comment by EugeneSnihovsky** [comment]
@Gnito Your answer is really helpful. Thanks for support :)
