### ISSUE TITLE
TypeError: sdk.images.upload is not a function

### ISSUE THREAD

**Issue by ollieh-m** [sharetribe/flex-template-web#840]
Now that image uploads use `sdk.images.upload` (as of https://github.com/sharetribe/flex-template-web/pull/829), we are getting the above error when trying to add an image to a listing. It looks to me like the SDK should have `images.upload` defined OK. Are we missing something?

Many thanks!

**Comment by Gnito** [comment]
@ollieh-m, that PR cotained an update to SDK in package.json. Did you fetch updated package with `yarn`?

**Comment by ollieh-m** [comment]
@Gnito I thought I had - but I just retried and now I'm not getting the error. The update to the SDK was just adding 'process_transitions/query' endpoints to the endpoints array - would that have been relevant?

**Comment by Gnito** [comment]
@ollieh-m, Between current commit hash and previous one, there was other endpoints added too.

Side note: we should start adding releases to SDK repo too.

**Comment by ollieh-m** [comment]
Ah thanks, that explains it. 
Yeah it was a bit tricky (without a release version) checking we did actually have the correct version of the SDK in our node modules.

**Comment by Gnito** [comment]
Cool, I'll close this issue now and add SDK releases/changelog to our backlog.
